// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBW7FTGxv9k0fK8thvo54ITMIDh1UaBsE',
    appId: '1:690493485282:android:237e415917ac8755b4aebb',
    messagingSenderId: '690493485282',
    projectId: 'mbti-softengen',
    storageBucket: 'mbti-softengen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYsiPTg9S882vAxsv8bUSlul4wbYUhal4',
    appId: '1:690493485282:ios:cb248bd2a071f93fb4aebb',
    messagingSenderId: '690493485282',
    projectId: 'mbti-softengen',
    storageBucket: 'mbti-softengen.appspot.com',
    androidClientId: '690493485282-2ebadnc1jida17c8u06ava9vqrh9e6de.apps.googleusercontent.com',
    iosClientId: '690493485282-e9mu0bgb6c8kmj195rs68rn1co2nehir.apps.googleusercontent.com',
    iosBundleId: 'com.example.mbtiApp',
  );
}
